import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/app/provider";
import NextAuthProvider from "@/app/NextAuthProvider";
import Header from "@/components/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-4 max-w-6xl">
          <NextAuthProvider>
            <Providers>
              <Header />
              {children}
            </Providers>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
